apiVersion: v1
kind: ConfigMap
metadata:
  name: git-lfs-minio-config
data:
  config.json: |
    {
      "serverListenAddr": ":8080",
      "minioHost": "10.18.96.201:38814",
      "minioAccessKey": "minio",
      "minioSecretKey": "minio123",
      "minioBucket": "git-lfs",
      "minioURLExpires": 3600
    }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: git-lfs-minio
  name: git-lfs-minio-service
spec:
  ports:
  - name: http-tf-serving
    port: 8080
    targetPort: 8080
  selector:
    app: git-lfs-minio
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: git-lfs-minio
  name: git-lfs-minio-v1
spec:
  selector:
    matchLabels:
      app: git-lfs-minio
  template:
    metadata:
      labels:
        app: git-lfs-minio
        version: v1
    spec:
      containers:
      - image: harbor.ainnovation.com/photon/git-lfs-minio:1.0.0
        imagePullPolicy: IfNotPresent
        name: git-lfs-minio
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /opt/config.json
          subPath: config.json
      volumes:
      - name: config
        configMap:
          name: git-lfs-minio-config
